/*
 * This header provides constants for DRA7 ATL (Audio Tracking Logic)
 *
 * The constants defined in this header are used in dts files
 *
 * Copyright (C) 2013 Texas Instruments, Inc.
 *
 * Peter Ujfalusi <peter.ujfalusi@ti.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _DT_BINDINGS_CLK_NXP2120_H
#define _DT_BINDINGS_CLK_NXP2120_H

#define CLKENB_TYPE_PCLK 				(0x08)
#define CLKENB_TYPE_PCLK_CLKENB			(0x0C)
#define CLKENB_TYPE_PCLK_CLKENB_BCLK	(0x0F)
#define CLKENB_TYPE_PCLK_BCLK			(0x0B)

#define CLKENB_MASK_PCLK				(0x08)
#define CLKENB_MASK_CLKENB				(0x04)
#define CLKENB_MASK_BCLK				(0x03)

#define CLKENB_ACCESS_REG16				(0x10000)


#define CLKGEN_TYPE_GEN0LH_GEN1LH		(4 << 8)
#define CLKGEN_TYPE_GEN0_GEN1 			(3 << 8)
#define CLKGEN_TYPE_GEN0L_GEN0H_GEN1	(2 << 8)
#define CLKGEN_TYPE_GEN0L_GEN0H			(1 << 8)
#define CLKGEN_TYPE_GEN0    			(0 << 8)

#define CLKGEN_TYPE_OUTCLK_ENB			(1 << 7)
#define CLKGEN_TYPE_OUTCLK_INV			(1 << 6)
#define CLKGEN_TYPE_GEN_OUTCLK			(3 << 6)

#define CLKGEN_TYPE_NODIV				(3 << 4)
#define CLKGEN_TYPE_DIV_10_5			(2 << 4)
#define CLKGEN_TYPE_DIV_9_5				(1 << 4)
#define CLKGEN_TYPE_DIV_12_5			(0 << 4)

#define CLKGEN_TYPE_PLL0_PLL1_SVLK_PSVLCK_IPSVCLK_AVCLK_ISVCLK	(8 << 0)
#define CLKGEN_TYPE_PLL0_PLL1_XTI 						(7 << 0)
#define CLKGEN_TYPE_EXTCLK 								(6 << 0)
#define CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK_AV_IAV_GEN0	(5 << 0)
#define CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK_AV_IAV			(4 << 0)
#define CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK				(3 << 0)
#define CLKGEN_TYPE_PCLK_PLL0_PLL1						(2 << 0)
#define CLKGEN_TYPE_PLL0_PLL1							(1 << 0)


#define CLKENB_TYPE_TIMER				(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_TIMER				(CLKGEN_TYPE_PLL0_PLL1 | CLKGEN_TYPE_OUTCLK_INV | CLKGEN_TYPE_OUTCLK_ENB)

#define CLKENB_TYPE_SSP					(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_SSP					(CLKGEN_TYPE_PLL0_PLL1)

#define CLKENB_TYPE_UART				(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_UART				(CLKGEN_TYPE_PLL0_PLL1 | CLKGEN_TYPE_DIV_10_5)

#define CLKENB_TYPE_AUDIO				(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_AUDIO				(CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK_AV_IAV | CLKGEN_TYPE_GEN0_GEN1)

#define CLKENB_TYPE_SDMMC				(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_SDNNC				(CLKGEN_TYPE_PCLK_PLL0_PLL1)

#define CLKENB_TYPE_VIP					(CLKENB_TYPE_PCLK_CLKENB_BCLK)
#define CLKGEN_TYPE_VIP 				(CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK | CLKGEN_TYPE_GEN_OUTCLK | CLKGEN_TYPE_GEN0L_GEN0H)

#define CLKENB_TYPE_I2C 				(CLKENB_TYPE_PCLK)
#define CLKGEN_TYPE_I2C					(0)

#define CLKENB_TYPE_USBDEV				(CLKENB_TYPE_PCLK_CLKENB_BCLK)
#define CLKGEN_TYPE_USBDEV				(CLKGEN_TYPE_EXTCLK | CLKGEN_TYPE_DIV_10_5 | CLKGEN_TYPE_GEN_OUTCLK | CLKGEN_TYPE_GEN0L_GEN0H)

#define CLKENB_TYPE_USBHOST				(CLKENB_TYPE_PCLK_CLKENB_BCLK)
#define CLKGEN_TYPE_USBHOST				(CLKGEN_TYPE_EXTCLK | CLKGEN_TYPE_NODIV | CLKGEN_TYPE_GEN_OUTCLK | CLKGEN_TYPE_GEN0L_GEN0H)

#define CLKENB_TYPE_PPM 				(CLKENB_TYPE_PCLK_CLKENB | CLKENB_ACCESS_REG16)
#define CLKGEN_TYPE_PPM					(CLKGEN_TYPE_PLL0_PLL1_XTI | CLKGEN_TYPE_OUTCLK_INV | CLKGEN_TYPE_GEN0L_GEN0H)

#define CLKENB_TYPE_PWM 				(CLKENB_TYPE_PCLK_CLKENB | CLKENB_ACCESS_REG16)
#define CLKGEN_TYPE_PWM					(CLKGEN_TYPE_PLL0_PLL1_ICLK_IICLK_AV_IAV | CLKGEN_TYPE_OUTCLK_INV | CLKGEN_TYPE_DIV_10_5 | CLKGEN_TYPE_GEN0L_GEN0H)

#define CLKENB_TYPE_ADC 				(CLKENB_TYPE_PCLK)
#define CLKGEN_TYPE_ADC					(0)

#define CLKENB_TYPE_MLC					(CLKENB_TYPE_PCLK_BCLK)
#define CLKGEN_TYPE_MLC					(0)

#define CLKENB_TYPE_DPC					(CLKENB_TYPE_PCLK_CLKENB)
#define CLKGEN_TYPE_DPC					(CLKGEN_TYPE_PLL0_PLL1_SVLK_PSVLCK_IPSVCLK_AVCLK_ISVCLK | CLKGEN_TYPE_GEN0LH_GEN1LH)

#define CLKENB_TYPE_ROTATOR				(CLKENB_TYPE_PCLK_BCLK)
#define CLKGEN_TYPE_ROTATOR				(0)

#define CLKENB_TYPE_SCALER				(CLKENB_TYPE_PCLK_BCLK)
#define CLKGEN_TYPE_SCALER				(0)

#define CLKENB_TYPE_DEINT				(CLKENB_TYPE_PCLK_BCLK)
#define CLKGEN_TYPE_DEINT				(0)

#define CLKENB_TYPE_CSC					(CLKENB_TYPE_PCLK_BCLK)
#define CLKGEN_TYPE_CSC					(0)

#endif
